apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    labels:
        app.kubernetes.io/name: fun0-http-mjs
    name: fun0-http-mjs
    namespace: default
spec:
    env:
        - name: CE-SOURCE
          valueFrom:
            configMapKeyRef:
                key: ce-source
                name: workflow-config
        - name: PUSH-TO-EVENTTYPE
          valueFrom:
            configMapKeyRef:
                key: fun0-publish-event-type
                name: workflow-config
    runtime: nodejs22
    resourceConfiguration:
      function:
        profile: XS
      build:
        profile: fast
    source:
        inline:
            dependencies: |
                {
                  "type": "module",
                  "dependencies": {
                      "uuid": "11.1.0"
                  }
                }
            source: |
              import { v4 as uuid_v4 } from "uuid";
              export async function main(event, context) {
                const payload={
                        uuid: uuid_v4(),
                        check_in: {
                          fun0: new Date(),
                        },
                        fibo: {
                          fun0: 0,
                        },
                };
                const eventType = process.env['PUSH-TO-EVENTTYPE'];
                const eventSource = process.env['CE-SOURCE'];
                
                let request = event.emitCloudEvent(eventType, eventSource, payload);
                request.then((response)=>{
                  console.log(response.request.getHeaders());
                  console.log(response.headers);
                  console.log(`Payload pushed to ${eventType}`,payload);
                }).catch((e)=>{
                  console.error(e)
                })
                
                return payload;
                }
