apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: fun7-secret-mount
spec:
  runtime: python312
  source:
    inline:
      source: |
        from os import path
        DATA_PATH = path.join("mountpoint", "foo")
        def main(event, context):
          with open(DATA_PATH, "r") as f:
            data = f.read()
            return data
  secretMounts:
    - secretName: dummy
      mountPath: mountpoint
  resourceConfiguration:
    function:
      profile: S
    build:
      profile: slow