name: fun0-http
namespace: default
runtime: nodejs14
source:
    sourceType: inline
apiRules:
    - name: fun0-http
      service:
        host: input
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow
env:
    - name: CE-SOURCE
      valueFrom:
        configMapKeyRef:
            name: workflow-config
            key: ce-source
    - name: PUSH-TO-EVENTTYPE
      valueFrom:
        configMapKeyRef:
            name: workflow-config
            key: fun0-publish-event-type
            
