apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
    creationTimestamp: null
    name: azure-devops-basic
    namespace: default
spec:
    auth:
        secretName: azure-repo-basic
        type: basic
    url: https://kyma-wookiee@dev.azure.com/kyma-wookiee/kyma-function/_git/azure-devops-sample2

---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
    creationTimestamp: null
    name: fun5-azure-devops-node-basic
    namespace: default
spec:
    baseDir: /fun4-azure-devops-node
    env:
        - name: PUSH_EVENT_TYPE
          valueFrom:
            configMapKeyRef:
                key: fun5-publish-event-type
                name: workflow-config
        - name: FIBONACCI_MIN
          valueFrom:
            configMapKeyRef:
                key: nodeFibonacciMin
                name: function-computation-config
        - name: FIBONACCI_MAX
          valueFrom:
            configMapKeyRef:
                key: nodeFibonacciMax
                name: function-computation-config
    reference: main
    runtime: nodejs14
    source: azure-devops-basic
    type: git

---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
    creationTimestamp: null
    name: fun5-azure-devops-node
    namespace: default
spec:
    filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.ready.for.fun5.v1
    protocol: ""
    protocolsettings: {}
    sink: http://fun5-azure-devops-node-basic.default.svc.cluster.local

