apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    creationTimestamp: null
    labels:
        app.kubernetes.io/name: fun7-finish
    name: fun7-finish
    namespace: default
spec:
    env:
        - name: FUNCTION_MAX_INDEX
          valueFrom:
            configMapKeyRef:
                key: last-function-index
                name: workflow-config
    runtime: nodejs18
    source:
        inline:
            dependencies: |-
                {
                  "name": "function-great-artur6",
                  "version": "0.0.1",
                  "dependencies": {
                  }
                }
            source: "module.exports = {    \n    main: function (event, context) {\n        if (!signInPassed(event.data)) {\n            res = event.extensions.response;\n            res.status(500)\n            return\n        }\n        return \"OK\"\n    }\n}\n\n\nfunction signInPassed(payload) {\n    let passed = true;\n    let max = parseInt(process.env['FUNCTION_MAX_INDEX'],10)\n    for (let i = 0; i <= max; i++) {\n        if(!payload.check_in[`fun${i}`]){\n            console.log(`Fun${i} hasn't check in...`)\n            return false\n        }\n        if(payload.fibo[`fun${i}`]==undefined){\n            console.log(`Fun${i} hasn't calculated fibo...`)\n            return false\n        }\n        console.log(`Check for Fun${i} passed!`)\n    }\n    return passed;\n}\n"

---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
    creationTimestamp: null
    name: fun7-finish
    namespace: default
spec:
    filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.ready.for.fun7.v1
    protocol: ""
    protocolsettings: {}
    sink: http://fun7-finish.default.svc.cluster.local

