apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
    name: fun5-azure-devops-node-basic
    namespace: default
spec:
    sink: http://fun5-azure-devops-node-basic.default.svc.cluster.local
    source: "testapp"
    types:
    - ready.for.fun5.v1
