apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: fun7-secret-mount
spec:
  hosts:
  - foo-secret
  service:
    name: fun7-secret-mount
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
  - path: /*
    methods: ["GET"]
    noAuth: true
