apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: fun8-inject-envs
spec:
  hosts:
  - envs
  service:
    name: fun8-inject-envs
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
  - path: /*
    methods: ["GET"]
    noAuth: true
