name: fun1-inline-node14
namespace: default
runtime: nodejs18
source:
    sourceType: inline
subscriptions:
    - name: fun1-inline-node14
      namespace: default
      protocol: ""
      filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.ready.for.fun1.v1
env:
    - name: PUSH_EVENT_TYPE
      valueFrom:
        configMapKeyRef:
            name: workflow-config
            key: fun1-publish-event-type
    - name: FIBONACCI_MIN
      valueFrom:
        configMapKeyRef:
            name: function-computation-config
            key: nodeFibonacciMin
    - name: FIBONACCI_MAX
      valueFrom:
        configMapKeyRef:
            name: function-computation-config
            key: nodeFibonacciMax